spring:
  datasource:
    url: jdbc:mysql://120.25.203.58:3317/db_smart?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456

logging:
  level:
    com.smart.rest: debug