spring:
  datasource:
    url: jdbc:mysql://120.25.203.58:3317/smart_address?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
logging:
  config: classpath:logback-spring-dev.xml
  level:
    com.smart.address: debug